services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
    deploy:  
      replicas: 1  

  carbon-intensity-api:
    build: 
      context: ../.
      dockerfile: ./carbon-intensity-api/Dockerfile
    networks:
      - backend
    depends_on:
      - redis
    deploy:
      replicas: 3
    environment:
      - APP__RATE_LIMITER__REDIS_SERVER__HOST=redis

  load_balancer:
    image: nginx:1.23.3-alpine-slim
    ports:
      - "8080:8080"
    volumes: 
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - carbon-intensity-api
    networks:
      - backend

networks:
  backend: