services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
    deploy:  
      # TODO: check if we can demo more replicas  
      replicas: 1  

  carbon-intensity-api:
    build: .
    networks:
      - backend
    depends_on:
      - redis
    deploy:
      replicas: 3

  load_balancer:
    image: nginx:1.23.3-alpine-slim
    ports:
      - "8080:8080"
    volumes: 
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - carbon-intensity-api
    networks:
      - backend

networks:
  backend: