services:
  redis:
    image: redis:7.4.1-bookworm
    ports:
      - "6379"
    networks:
      - backend
    deploy:  
      replicas: 1

  carbon-intensity-api:
    build: 
      context: ../.
      dockerfile: ./carbon-intensity-api/Dockerfile
    networks:
      - backend
    depends_on:
      - redis
    deploy:
      replicas: 3
    environment:
      - APP__RATE_LIMITER__REDIS_SERVER__HOST=redis

  load-balancer:
    image: nginx:1.23.3-alpine-slim
    ports:
      - "8080:8080"
    volumes: 
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - carbon-intensity-api
    networks:
      - backend
  
  jaeger:
    image: jaegertracing/jaeger:2.1.0
    ports:
      - "16686:16686"
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    depends_on:
      - jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
      - "3000:3000"
    volumes:
      - "./otel-collector.yaml:/etc/otelcol-contrib/config.yaml"

networks:
  backend: