name: Carbon intensity API CI

defaults:
  run:
    working-directory: carbon-intensity-api

on:
  push:
    paths:
      - 'carbon-intensity-api/**'

jobs:
  build_and_test:
    services:
      redis:
        image: redis:alpine
        ports:
          - 7379:6379
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Build
        run: cargo build
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy -- -Dwarnings
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test
        run: cargo nextest run
      - name: Doc test
        run: cargo test --doc

  distributed_test:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4
      - name: Boot distributed app setup 
        run: docker compose up -d
      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./carbon-intensity-api/distributed_test.js